### ISSUE TITLE
supporting atom-one-dark-theme on melpa stable

### ISSUE THREAD

**Issue by ghost** [jonathanchu/atom-one-dark-theme#14]
_atom-one-dark-theme_ isn't available on [melpa-stable](https://stable.melpa.org/). Can you make this theme available on melpa-stable?

**Comment by jonathanchu** [comment]
Oh! Sure thing, I'll look to get this up on there this weekend.

**Comment by jonathanchu** [comment]
@sixpointzero this should be available on Melpa Stable now.  Thanks for the heads-up here!

**Comment by ghost** [comment]
@jonathanchu Thanks for supporting it on melpa-stable. Awesome work porting atom-one-dark to Emacs!

**Comment by jonathanchu** [comment]
@sixpointzero :beers: 😸
