### ISSUE TITLE
What type of font is this?

### ISSUE THREAD

**Issue by iuunhao** [jonathanchu/atom-one-dark-theme#16]
What type of font is this?

**Comment by jonathanchu** [comment]
Hey @iuunhao!  If you're referring to this [screenshot](https://camo.githubusercontent.com/e6565f770c800f41f2b60cc3c06079a39b11e169/687474703a2f2f692e696d6775722e636f6d2f71446e6c4559632e706e67), I'm using Inconsolata in it.  

http://levien.com/type/myfonts/inconsolata.html
