### ISSUE TITLE
Installation failure: Symbol's value as variable is void: atom-one-dark-colors-alist

### ISSUE THREAD

**Issue by mtesseract** [jonathanchu/atom-one-dark-theme#2]
Hi,

I have just  tried to install the atom-one-dark-theme via M-x package-install.
This resulsts in the following error:

```
Leaving directory `/home/moreek/.emacs.d/elpa/atom-one-dark-theme-20150806.2117'
Compiling file /home/moreek/.emacs.d/elpa/atom-one-dark-theme-20150806.2117/atom-one-dark-theme-pkg.el at Fri Oct  2 13:15:38 2015
Entering directory `/home/moreek/.emacs.d/elpa/atom-one-dark-theme-20150806.2117/'
Compiling file /home/moreek/.emacs.d/elpa/atom-one-dark-theme-20150806.2117/atom-one-dark-theme.el at Fri Oct  2 13:15:38 2015
atom-one-dark-theme.el:48:1:Error: Symbol's value as variable is void: atom-one-dark-colors-alist
```

Did I overlook something?

Thanks
~ Moritz

**Comment by jonathanchu** [comment]
Hi @mtesseract - interesting... can you tell me what version of Emacs you're on?  It sounds like something went awry with compiling.

Thanks!

**Comment by mtesseract** [comment]
Sorry, of course. I am running Emacs 24.5.1 on Arch Linux. What is weird is that I seem to be able to load the theme alright via:

```
(add-to-list 'custom-theme-load-path "~/.emacs.d/elpa/atom-one-dark-theme-20150806.2117/")
(load-theme 'atom-one-dark t)
```

The above error message only appeared during package installation.

**Comment by jonathanchu** [comment]
No need to apologize :)  So it _sounds_ like the initial compile of the package failed for some reason, hence the errors you saw.  My guess is when you loaded the package during Emacs startup, it re-compiled and succeeded.

Without knowing what your config looks like or how you have your package management config set up, perhaps you need to add `(require 'compile)` to avoid this issue if it happens again?

**Comment by jonathanchu** [comment]
@mtesseract I'm going to close this out for now as it seems to be OK for you.  Let me know if there's something else I'm missing here if this becomes an issue again. :beers:

**Comment by mtesseract** [comment]
Hi @jonathanchu 
please excuse my late reply. Reason is that I hadn't had time yet to really debug this. But I have verified that the problem is still there. M-x package-install fails, regardless of wether I explicitely add (require 'compile) to my .emacs or not.
Thanks

**Comment by jonathanchu** [comment]
Ah ok thanks - I misunderstood that it was building correctly for you.  I'll look into this more then.

**Comment by jonathanchu** [comment]
@mtesseract I believed I fixed it.  It was a silly config thing - fb9ecce.

Would you mind re-installing this package and see if this fixed the issue for you?  At your convenience, of course :)

**Comment by mtesseract** [comment]
Nice! Seems to fix the issue for me. :-)
Thank you very much

**Comment by jonathanchu** [comment]
@mtesseract :beers: !! Thanks for reporting it, I definitely overlooked that.
