### ISSUE TITLE
Doesn't set linum colors

### ISSUE THREAD

**Issue by mlsteele** [jonathanchu/atom-one-dark-theme#22]
Awesome theme, thanks! I've got one problem. After `load-theme`ing the theme, it doesn't set linum colors so the linum bar is left with its colors from my old theme.

![screenshot 2016-10-13 10 55 56](https://cloud.githubusercontent.com/assets/705646/19354180/db3dfdb4-9133-11e6-8f26-28e4d0dff96e.png)

**Comment by jonathanchu** [comment]
Hi @mlsteele!  @rski was kind enough to fix this, let me know if this addressed your issue.

**Comment by mlsteele** [comment]
Yep, that did it. Thanks to you both :)
