### ISSUE TITLE
Support for latex mode

### ISSUE THREAD

**Issue by rski** [jonathanchu/atom-one-dark-theme#24]
The faces for latex are not customised properly, which results in this:

![2016-11-17-184536_379x74_escrotum](https://cloud.githubusercontent.com/assets/2960312/20398411/0ad54d06-acf6-11e6-865a-ed5618d8961b.png)

Same thing in atom:

![2016-11-17-184522_347x44_escrotum](https://cloud.githubusercontent.com/assets/2960312/20398445/296b3c9e-acf6-11e6-9b60-993b50b4f010.png)

**Comment by jonathanchu** [comment]
@jabberwocky0139 fixed this issue in #25 which has now been merged into `master`.  Please let me know if this does the trick for you and if not, we can re-open this until fixed.  Thanks! 😃

**Comment by rski** [comment]
It works like a charm, thanks @jabberwocky0139  & @jonathanchu :-). Sorry for taking so long to get back, took a while before i could upgrade the theme and test it.
