### ISSUE TITLE
Please specify the license for this package

### ISSUE THREAD

**Issue by tarsius** [jonathanchu/atom-one-dark-theme#28]
Could you please specify the license used for this package?

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this permission statement to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

Also consider adding a `LICENSE` file containing the [text of the GPL-3](https://www.gnu.org/licenses/gpl-3.0.txt). You could add just that file without also adding the above persmission statement, but if you do that, then the "or (at your option) any later version" bit won't be known. So I recommend that you add both the actual license and the permission statement.

If you find the permission statement to be too noisy, then you could instead add one of these following lines to the header.  If you do that, then it becomes more important to also add the `LICENSE` file - a judge might decide that such a line by itself is not sufficient.  Still, adding just such a line is better than not specifing the license at all.

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
;; License: GPL-3+
```

**Comment by jonathanchu** [comment]
Cheers, thanks @tarsius!  I'll take care of this today. 😺

**Comment by tarsius** [comment]
Thanks!

**Comment by jonathanchu** [comment]
@tarsius thanks again!  This was done in PR #29 which is in `master` now.

**Comment by tarsius** [comment]
:clinking_glasses:
