### ISSUE TITLE
Drop-down menu won't change themes?

### ISSUE THREAD

**Issue by kyojin-choo** [jonathanchu/atom-one-dark-theme#30]
I'm reposting this from the company-mode issues tab. However, per the title of this inquiry, the drop-down menu has an unpleasant aesthetic. Previously in my myinit.org, I incorporated this string of code to change the color scheme for company, which according to the EmacsWiki: Company-Mode adjusts the color scheme for dark backgrounds (I have removed this portion of code from myinit.org):

```
(require 'color)
(let ((bg (face-attribute 'default :background)))
(custom-set-faces
 `(company-tooltip ((t (:inherit default :background ,(color-lighten-name bg 2)))))
 `(company-scrollbar-bg ((t (:background ,(color-lighten-name bg 10)))))
 `(company-scrollbar-fg ((t (:background ,(color-lighten-name bg 5)))))
 `(company-tooltip-selection ((t (:inherit font-lock-function-name-face))))
 `(company-tooltip-common ((t (:inherit font-lock-constant-face))))))
```

However, since following this block of code, my emacs has a strange appearance now:

<img width="327" alt="screen shot 2017-08-18 at 12 43 29 am" src="https://user-images.githubusercontent.com/18727118/29479672-a7409786-8441-11e7-9558-bddcbc781e3a.png">

I'm currently using the Atom-One-Dark-Theme, and it incorporates its own tooltip theme. However, it will not change the tooltip/drop-down menu to the proper colors. Here is the following code in the atom-one-dark-theme.el:

```
;; company-mode
  `(company-tooltip ((t (:foreground ,atom-one-dark-fg :background ,atom-one-dark-bg-1))))
  `(company-tooltip-annotation ((t (:foreground ,atom-one-dark-mono-2 :background ,atom-one-dark-bg-1))))
   `(company-tooltip-selection ((t (:foreground ,atom-one-dark-fg :background ,atom-one-dark-gray))))
   `(company-tooltip-mouse ((t (:background ,atom-one-dark-gray))))
   `(company-tooltip-common ((t (:foreground ,atom-one-dark-orange-2 :background ,atom-one-dark-bg-1))))
   `(company-tooltip-common-selection ((t (:foreground ,atom-one-dark-orange-2 :background ,atom-one-dark-gray))))
  `(company-preview ((t (:background ,atom-one-dark-bg))))
  `(company-preview-common ((t (:foreground ,atom-one-dark-orange-2 :background ,atom-one-dark-bg))))
  `(company-scrollbar-fg ((t (:background ,atom-one-dark-mono-1))))
  `(company-scrollbar-bg ((t (:background ,atom-one-dark-bg-1))))

```
Sorry if there's some ambiguity in this post; I'll try to clear out any questions that you might have.

**Comment by jonathanchu** [comment]
Hey @kyoogoo!  Thanks for bringing this to my attention!  I didn't realize it was an issue.  

Can you link to the company issue that you mentioned above so I can get some context on what's going on with the theming?  Perhaps I missed something here, but I definitely do use `company` and haven't noticed this issue yet.

Cheers, thanks!  :beers:

**Comment by kyojin-choo** [comment]
Hey, I'm really sorry for the late reply. However, I decided to do a clean wipe and reinstallation of emacs and everything is functioning perfectly. I suppose it was just a strange glitch?

I tried to reenact the glitch but to no avail. I'll definitely let you know if it happens again! 

Cheers!

**Comment by jonathanchu** [comment]
@kyoogoo no worries and no need to apologize :) Glad to hear the issue turns out to not be an issue after all.
