### ISSUE TITLE
Unmatched braces are nigh invisible

### ISSUE THREAD

**Issue by thomasheartman** [jonathanchu/atom-one-dark-theme#46]
Unmatched parentheses, braces, and brackets in the editor turn black and are as good as invisible against the background. This makes it extremely hard to catch these errors and frequently leads to confusion when the syntax checker is complaining about unmatched braces. See the following screenshot for an example (there's a closing parenthesis immediately following the comma):
![Unmatched brace after the comma](https://user-images.githubusercontent.com/17786332/42256858-e49ad8c2-7f53-11e8-9280-4b2190e6ea7b.png)

If this is due to the emacs rainbow parens and out of your hands, then I apologize, but if it's something that can be handled on your end, it'd be great to see a different coloration for unmatched parens, brackets, and braces.

**Comment by thomasheartman** [comment]
Pfft. Never mind. This is me not doing enough research on my own. It's the rainbow delimiters package, and I can customize it at will. Apologies.

**Comment by thomasheartman** [comment]
Woah, okay. Sorry for reopening this. On further inspection, it appears that unmatched braces *are* set to be black in `atom-one-dark-theme.el`, and while it can be customized, it strikes me as a strange default for the theme, and as such may warrant a reconsideration.  I think I'll leave this issue open for now and await further comment. Thanks.

**Comment by jonathanchu** [comment]
Hey @t-hart!  Thanks for reporting this and for the great detail to get me started.  I'll take a closer look and see what's going on here.  Cheers!  🍻

**Comment by elektronaut** [comment]
It's indeed set to black, the culprit is here:

```emacs-lisp
`(rainbow-delimiters-unmatched-face ((t (:foreground ,atom-one-dark-black))))
```

I don't think the color choices for the various depths are great either. Cyan/blue, red-1/red-2 and orange-1/orange-2 are right next to each other and are hard to differentiate. 

I can take a look at improving it.

**Comment by elektronaut** [comment]
Before:

![screenshot 2018-10-10 at 15 45 17](https://user-images.githubusercontent.com/5549/46740630-9c5ee380-cca3-11e8-8d7e-3ba22f3cfbca.png)

After:

![screenshot 2018-10-10 at 15 45 39](https://user-images.githubusercontent.com/5549/46740622-979a2f80-cca3-11e8-9ff0-e8e48651e8e6.png)
