### ISSUE TITLE
Wrong Colors

### ISSUE THREAD

**Issue by fennecinspace** [jonathanchu/atom-one-dark-theme#48]
I've followed the instruction in the README.md and this is what i get

![image](https://user-images.githubusercontent.com/9774613/46275373-9dca3680-c554-11e8-9909-bbaee44a03a5.png)

**Comment by daviderestivo** [comment]
Hi, 

most probably it is a problem of your terminal. Try to set it to xterm with 256 color support:

`
export TERM=xterm-256color
`

Regards,
Davide

**Comment by fennecinspace** [comment]
that did not work

**Comment by nnoodle** [comment]
That's how it's suppose to look like in 256 color displays. If you want proper colors in the terminal version, Emacs 26 got [true color support for the terminal](https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html#Colors-on-a-TTY), but most people would probably recommend you to use the GUI version of Emacs instead.

**Comment by fennecinspace** [comment]
@nnoodle i've tried this, it didn't work

**Comment by jonathanchu** [comment]
Hey @LogX7!  So you've tried using the GUI version and it still did not display this theme correctly?  Just want to make sure I understood you correctly.

Also, can you provide your Emacs version and OS?  Thanks! 😺
