### ISSUE TITLE
Annotation background color in company selection is inconsistent with the rest of the line

### ISSUE THREAD

**Issue by finalpatch** [jonathanchu/atom-one-dark-theme#54]
https://github.com/jonathanchu/atom-one-dark-theme/blob/073a30cb86148ef3e00812e08cd844168acff0c5/atom-one-dark-theme.el#L133

Thsi can be fixed with adding company-tooltip-annotation-selection face,  that combines the annotation foreground and selection background color:
```
   `(company-tooltip-annotation-selection ((t (:foreground ,atom-one-dark-mono-2 :background ,atom-one-dark-gray))))
```

**Comment by jonathanchu** [comment]
Oh nice, good catch!  I'm unfamiliar with this, but should this replace `company-tooltip-annotation` or be added with `company-tooltip-annotation` unmodified?

Also happy to accept a PR for this if you know how to confirm it's good to go, I don't use `company` nearly as much as I should so I might miss the change if it's subtle. 😄

**Comment by finalpatch** [comment]
Add

**Comment by jonathanchu** [comment]
Cheers, thanks @finalpatch!  Just pushed that to `master`.
