### ISSUE TITLE
Ediff buffers have rather unreadable highlights

### ISSUE THREAD

**Issue by ianyepan** [jonathanchu/atom-one-dark-theme#62]
Here are a couple of screenshots that showcases the highlights in ediff. They are sadly non-consistent with the atom-one-dark colourscheme, and appears to be rather unreadable.
<img width="1280" alt="Screenshot 2020-03-22 at 13 04 20" src="https://user-images.githubusercontent.com/36686900/77243054-61a2fe00-6c40-11ea-9526-7553f9bf68d3.png">
<img width="1280" alt="Screenshot 2020-03-22 at 13 04 34" src="https://user-images.githubusercontent.com/36686900/77243056-636cc180-6c40-11ea-9568-3b1aa65f225d.png">

### My fixes

I have spent some time to experiment with the most opitmal colours, if I may kindly suggest:

```emacs-lisp
  (ediff-fine-diff-A    ((t (:background "#885555"))))
  (ediff-fine-diff-B    ((t (:background "#558855"))))
  (ediff-fine-diff-C    ((t (:background "#555588"))))
  (ediff-current-diff-A ((t (:background "#663333"))))
  (ediff-current-diff-B ((t (:background "#336633"))))
  (ediff-current-diff-C ((t (:background "#333366"))))
  (ediff-even-diff-A    ((t (:background "#181a1f"))))
  (ediff-even-diff-B    ((t (:background "#181a1f"))))
  (ediff-even-diff-C    ((t (:background "#181a1f"))))
  (ediff-odd-diff-A     ((t (:background "#181a1f"))))
  (ediff-odd-diff-B     ((t (:background "#181a1f"))))
  (ediff-odd-diff-C     ((t (:background "#181a1f"))))
```

Here's how it looks like afterwards:

<img width="1280" alt="Screenshot 2020-03-22 at 13 25 06" src="https://user-images.githubusercontent.com/36686900/77243075-9b740480-6c40-11ea-95ed-d21d2159fcdb.png">
<img width="1279" alt="Screenshot 2020-03-22 at 13 25 16" src="https://user-images.githubusercontent.com/36686900/77243076-9e6ef500-6c40-11ea-8227-0e8604cb0501.png">

**Comment by ianyepan** [comment]
Friendly ping

**Comment by jonathanchu** [comment]
Hi @ianpan870102, I'm so sorry for the embarrassingly long delay in response here!

And sure, this is likely just an oversight that was missed! Feel free to make a PR, I'd gladly merge it in ASAP.  If you're busy I can certainly add this in within the next day or two, but I'd want to give credit where it's due 😸

**Comment by ianyepan** [comment]
Hi @jonathanchu don't be! Glad you reached back 👍 
I just created a PR with the colours I suggested above. Ready for your review.
